version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql  

  web:
    build: .
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    env_file: .env
    restart: always
    environment:
      RAILS_ENV: development
    depends_on:
      - db
    command: chmod u+x /myapp/bin/entry.sh
    entrypoint: ["bin/entry.sh"]
    
volumes:
  db_data:
